=== cerenmert14/etna-cli/schemas/test.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["language", "workload", "mutations", "trials", "timeout", "tasks"],
    "properties": {
      "language": {
        "type": "string"
      },
      "workload": {
        "type": "string"
      },
      "mutations": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "trials": {
        "type": "integer",
        "minimum": 1
      },
      "timeout": {
        "type": "number",
        "exclusiveMinimum": 0
      },
      "cross": {
        "type": "boolean"
      },
      "params": {
        "type": "object",
        "properties": {
          "tests": {
            "type": "integer",
            "minimum": 1
          }
        },
        "additionalProperties": false
      },
      "tasks": {
        "type": "array",
        "items": {
          "type": "object",
          "required": ["strategy", "property"],
          "properties": {
            "strategy": {
              "type": "string"
            },
            "property": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      }
    },
    "additionalProperties": false
  }
}

=== cerenmert14/etna-cli/workloads/OCaml/BST/bst.json
[
    {
        "language": "OCaml",
        "workload": "BST",
        "mutations": ["insert_1"],
        "trials": 10,
        "timeout": 60,
        "tasks": [
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertPost"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertModel"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_DeleteInsert"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertInsert"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertUnion"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionDeleteInsert"
            }
        ]
    },
    {
        "language": "OCaml",
        "workload": "BST",
        "mutations": ["insert_2"],
        "trials": 10,
        "timeout": 60,
        "tasks": [
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertPost"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertModel"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertDelete"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_DeleteInsert"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertInsert"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertUnion"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionDeleteInsert"
            }
        ]
    },
    {
        "language": "OCaml",
        "workload": "BST",
        "mutations": ["insert_3"],
        "trials": 10,
        "timeout": 60,
        "tasks": [
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertPost"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertModel"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertDelete"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertInsert"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertUnion"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionDeleteInsert"
            }
        ]
    },
    {
        "language": "OCaml",
        "workload": "BST",
        "mutations": ["delete_4"],
        "trials": 10,
        "timeout": 60,
        "tasks": [
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_DeleteModel"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_DeletePost"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_DeleteDelete"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_DeleteInsert"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_DeleteUnion"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertDelete"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionDeleteInsert"
            }
        ]
    },
    {
        "language": "OCaml",
        "workload": "BST",
        "mutations": ["delete_5"],
        "trials": 10,
        "timeout": 60,
        "tasks": [
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_DeleteModel"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_DeletePost"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_DeleteDelete"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_DeleteInsert"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_DeleteUnion"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionDeleteInsert"
            }
        ]
    },
    {
        "language": "OCaml",
        "workload": "BST",
        "mutations": ["union_6"],
        "trials": 10,
        "timeout": 60,
        "tasks": [
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionValid"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionPost"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionModel"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_DeleteUnion"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertUnion"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionDeleteInsert"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionUnionAssoc"
            }
        ]
    },
    {
        "language": "OCaml",
        "workload": "BST",
        "mutations": ["union_7"],
        "trials": 10,
        "timeout": 60,
        "tasks": [
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionValid"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionPost"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionModel"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_DeleteUnion"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertUnion"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionDeleteInsert"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionUnionAssoc"
            }
        ]
    },
    {
        "language": "OCaml",
        "workload": "BST",
        "mutations": ["union_8"],
        "trials": 10,
        "timeout": 60,
        "tasks": [
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionPost"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionModel"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_DeleteUnion"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_InsertUnion"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionDeleteInsert"
            },
            {
                "strategy": "gen_Q_Bespoke",
                "property": "prop_Q_UnionUnionAssoc"
            }
        ]
    }
]

=== cerenmert14/etna-cli/templates/tests/t2.json
[
    {
        "language": "Racket",
        "workload": "BST",
        "mutations": ["insert_1"],
        "trials": 10,
        "timeout": 60,
        "tasks": [
            {
                "strategy": "RackcheckBespoke",
                "property": "test_prop_InsertPost"
            },
            {
                "strategy": "RackcheckBespoke",
                "property": "test_prop_InsertPost"
            }
        ]
    }
]
